version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
       - node/install:
        install-yarn: true
        node-version: latest
      - run: node --version
      - run: npm install
      - run: npm start
      - heroku/deploy-via-git
